let bookArchive = [
  {
    id: 1,
    formato: "Libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 2,
    formato: "revista",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "22Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 3,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "a Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 4,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "b Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 5,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 6,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Humano demaciado humano",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 7,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 8,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 9,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 10,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 11,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 12,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 13,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 14,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 15,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 16,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 17,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 18,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 19,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 20,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 21,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 22,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 23,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 24,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 25,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 26,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 27,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 28,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 29,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 30,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 31,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 32,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 33,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 34,
    formato: "Libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 35,
    formato: "revista",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 36,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "a Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 37,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "b Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 38,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 39,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Humano demaciado humano",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 40,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 41,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 42,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 43,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 44,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 45,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 46,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 47,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 48,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 49,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 50,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 52,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 53,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 54,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 55,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 56,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 57,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 58,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 59,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 60,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 61,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 62,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 63,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 64,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 65,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 66,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 67,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },{
    id: 68,
    formato: "Libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 69,
    formato: "revista",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 70,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "a Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 71,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "b Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 72,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 73,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Humano demaciado humano",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 74,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 75,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 76,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 77,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 78,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 79,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 80,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 81,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 82,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 83,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 84,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 85,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 86,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 87,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 88,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 89,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 90,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 91,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 92,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 93,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 94,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 95,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 96,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 97,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 98,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 99,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 100,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },{
    id: 101,
    formato: "Libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 102,
    formato: "revista",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 103,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "a Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 104,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "b Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 105,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 106,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Humano demaciado humano",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 107,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 108,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 109,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 110,
    formato: "libro",
    pnf: "Informatica",
    materia: "Programacion",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 111,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 112,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 113,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 114,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 115,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 116,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 117,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 118,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 119,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 120,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 121,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 122,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 123,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 124,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 125,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 126,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 127,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 128,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 129,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 130,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 131,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 132,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 133,
    formato: "libro",
    pnf: "Informatica",
    materia: "Proyecto",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },{
    id: 134,
    formato: "Libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 135,
    formato: "revista",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "1 1Metodología de investigación 4 edicion",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_4.PNG",
    link: "https://drive.google.com/file/d/1ag9qWOdxXLB5aMz8MK6Gs7u8w-tCmk0w/view?usp=sharing",
  },
  {
    id: 136,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "a Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  {
    id: 137,
    formato: "libro",
    pnf: "Informatica",
    materia: "Matematica",
    nombre: "aasd Metodología de investigación Para qué",
    desc: "Este libro se suma a la extensa y variada producción sobre cuestiones metodológicas. No pretendemos ofreceruna mirada original ni fundacional sobre estos saberes, solo aspiramos a participar y tomar posición frente a algunas de las reflexiones y debates que transitan por las aulas",
    img: "/Blioteca-de-IUTM/imgbooks/metodologia_de_la_investigacion_para_que.PNG",
    link: "https://drive.google.com/file/d/18WUR4_UE2DB5z7hdtbVg21fOwY0Pgmqh/view?usp=sharing",
  },
  
  
];
